---
kind: pipeline
type: docker
name: union-pay

steps:
- name: ssh commands
  image: appleboy/drone-ssh
  settings:
    host: 172.17.0.1
    username: zhangqiang
    key:
      from_secret: id_rsa
    port: 22
    script:
      - cd docker
      - sudo rm -rf union-pay/postgres
      - sudo rm -rf union-pay/redis
      - sudo rm -rf union-pay

trigger:
  event:
  - push
