---
kind: pipeline
type: docker
name: union-pay

steps:
- name: ssh commands
  image: appleboy/drone-ssh
  settings:
    host: 172.17.0.1
    username: zhangqiang
    key:
      from_secret: id_rsa
    port: 22
    script:
      - cd docker/union-pay
      - docker-compose down -v
      - cd ..
      - rm -rf union-pay
      - git clone https://github.com/tyokyo320/union-pay.git docker/union-pay
      - cd union-pay
      - docker-compose up -d --build



trigger:
  event:
  - push
