# postgresql connect configuration
postgresql:
  host: "postgres"
  port: "5432"
  user: "test"
  password: "test"
  db: "test"
  sslmode: "disable"
  timezone: "Asia/Tokyo"

# redis configuration
redis:
  addr: "redis:6379"
  password: ""
  db: 0
