# postgresql connect configuration
postgresql:
  host: "192.168.50.185"
  # host: "192.168.10.106"
  port: "5432"
  user: "test"
  password: "test"
  db: "test"
  sslmode: "disable"
  timezone: "Asia/Tokyo"

# redis configuration
redis:
  # addr: "192.168.10.106:6379"
  addr: "192.168.50.185:6379"
  password: ""
  db: 0
