# postgresql connect configuration
postgresql:
  host: "10.1.229.236"
  # host: "192.168.10.106"
  port: "5432"
  user: "test"
  password: "test"
  db: "test"
  sslmode: "disable"
  timezone: "Asia/Tokyo"

# redis configuration
redis:
  addr: "10.1.229.204:6379"
  # addr: "192.168.10.106:6379"
  password: ""
  db: 0
