---
name: build

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-server:
    runs-on: ubuntu-latest
    name: Build server
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set output
        id: meta
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      # - name: Login to harbor
      #   uses: docker/login-action@v1
      #   with:
      #     registry: ${{ secrets.DOCKER_REGISTRY }}
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Build, tag, and push image to register
      #   env:
      #     DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
      #     DOCKER_REPOSITORY: union-pay
      #     IMAGE_TAG: ${{ steps.meta.outputs.tag }}
      #   run: |
      #     docker build -t $DOCKER_REGISTRY/$DOCKER_REPOSITORY:$IMAGE_TAG .
      #     docker push $DOCKER_REGISTRY/$DOCKER_REPOSITORY:$IMAGE_TAG
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build, tag, and push image to register
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_REPOSITORY: union-pay
          IMAGE_TAG: ${{ steps.meta.outputs.tag }}
        run: |
          docker build -t $DOCKERHUB_USERNAME/$DOCKER_REPOSITORY:$IMAGE_TAG .
          docker push $DOCKERHUB_USERNAME/$DOCKER_REPOSITORY:$IMAGE_TAG